### ISSUE TITLE
注意力中的BN缺乏对照实验

### ISSUE THREAD

**Issue by splinter21** [NJU-Jet/FMEN#2]
论文很赞，工作比赛成绩也很赞！（基本是目前第一了，耗时就差一丁点）
BN重回SR让人眼前一亮，但是作为一个创新点（github创新点第三条），缺乏对照实验。
好奇如果删除了BN训，性能是怎样的？

**Comment by NJU-Jet** [comment]
谢谢您的认可！之后我们会将有关BN的实验整理发布。

**Comment by NJU-Jet** [comment]
删除了BN训练会随机不稳定，可能出现100轮训练后直接不收敛。偶尔收敛的情况下，PSNR相比有BN的模型PSNR在DIV2K上会低0.05，在Urban100上会低0.07左右。

**Comment by sdreamforchen** [comment]
> 删除了BN训练会随机不稳定，可能出现100轮训练后直接不收敛。偶尔收敛的情况下，PSNR相比有BN的模型PSNR在DIV2K上会低0.05，在Urban100上会低0.07左右。

您好。RRRB的conv3*3的channel数做过消融试验吗？  C 2C 4C之类的有过对比吗？   这个模块感觉可以作为其他任务的resnet的通用组件。

**Comment by NJU-Jet** [comment]
3C、4C和2C差不多，比C好一些，再扩大通道数效果反而更差了。考虑到训练时间开销，设为2C。&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: "sdreamforchen"; 
Date: 2022年5月24日(星期二) 中午11:38
To: "NJU-Jet/FMEN"; 
Cc: ***@***.***>; "Comment"; 
Subject: Re: [NJU-Jet/FMEN] 注意力中的BN缺乏对照实验 (Issue #2)

&nbsp;


  
删除了BN训练会随机不稳定，可能出现100轮训练后直接不收敛。偶尔收敛的情况下，PSNR相比有BN的模型PSNR在DIV2K上会低0.05，在Urban100上会低0.07左右。
  
您好。RRRB的conv3*3的channel数做过消融试验吗？  C 2C 4C之类的有过对比吗？   这个模块感觉可以作为其他任务的resnet的通用组件。

**Comment by sdreamforchen** [comment]
您好。我看您的重参数block，都是默认BN在conv前面？  这个有好处么？ 我看了2016年的老论文Identity Mappings in Deep Residual Networks。  难道是同理相似的？谢谢

**Comment by sdreamforchen** [comment]
感谢！我也正在做这个试验。如果适配coco，那在检测识别领域，也差不多可以说是无损的提升了运行速度。可以作为base trick了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月24日(周二) 中午1:08
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [NJU-Jet/FMEN] 注意力中的BN缺乏对照实验 (Issue #2)




 3C、4C和2C差不多，比C好一些，再扩大通道数效果反而更差了。考虑到训练时间开销，设为2C。&amp;nbsp; 
 &amp;nbsp; 
 ------------------&amp;nbsp;Original&amp;nbsp;------------------ 
 From: "sdreamforchen";  
 Date: 2022年5月24日(星期二) 中午11:38 
 To: "NJU-Jet/FMEN";  
 Cc: ***@***.***&gt;; "Comment";  
 Subject: Re: [NJU-Jet/FMEN] 注意力中的BN缺乏对照实验 (Issue #2) 
 
 &amp;nbsp; 
 
 
    
 删除了BN训练会随机不稳定，可能出现100轮训练后直接不收敛。偶尔收敛的情况下，PSNR相比有BN的模型PSNR在DIV2K上会低0.05，在Urban100上会低0.07左右。 
    
 您好。RRRB的conv3*3的channel数做过消融试验吗？  C 2C 4C之类的有过对比吗？   这个模块感觉可以作为其他任务的resnet的通用组件。

**Comment by MiaoJieF** [comment]
请问论文中的ERB不是比RB掉了一些精度吗？为什么说无损提升了运行速度？
